ALTER TABLE usuario RENAME TO usuarios;
ALTER TABLE usuarios DROP COLUMN IF EXISTS nome;
ALTER TABLE usuarios DROP COLUMN IF EXISTS uuid;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS login VARCHAR(255);
UPDATE usuarios SET login = '' WHERE login IS NULL;
ALTER TABLE usuarios ALTER COLUMN login SET NOT NULL;
ALTER TABLE usuarios ALTER COLUMN senha SET NOT NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS permissao VARCHAR(255);
UPDATE usuarios SET permissao = 'USER' WHERE permissao IS NULL;